### PR TITLE
Make it compile with LLVM

### PR DESCRIPTION
**Pull request by puffetto**
Hello,
Nowadays the official compiler on FreeBSD is LLVM; LLVM on FreeBSD is a bit picky about standard conformance: if you say "-D_POSIX_C_SOURCE=999999L" it means to compile making visible ONLY what is available in "the latest version on POSIX". In example "isascii()" is currecntly deprecated.
The PR should not affect any other platform, but I could not test on Linux.
With this change and the PR I submitted a few hours ago for tkrzw-rpc both things compile happily on FreeBSD/LLVM, link with systems-provided gRPC, abseil and protobuf ports, and so far seem to be quite stable.

### CODE REVIEW

**Comment by estraier** [comment]
In that case, I'd like to make my code be compatible to the LLVM requirement with -D_POSIX_C_SOURCE=999999L.
I myself has been making effort to avoid deprecated APIs.
What errors did you observe with -D_POSIX_C_SOURCE=999999L ?

**Comment by puffetto** [comment]
Yes, Clang+LLVM.

Point is that this is considered normal behaviour, some library functions that tkrzw uses are not in the posix standard (like memmem()) or have been removed in the most recent versions (like isalpha()); while they are provided on FreeBSD the system headers hide them if you ask to have current posix conformance.

For sure with D_POSIX_C_SOURCE=999999L on FreeBSD CLANG/LLVM hides isalpha() and memmem(); if you care I investigate more, but I am quite confident that at least on this platform not setting _POSIX_C_SOURCE is the best option.

Please notice that the proposed PR does not change anything on the other platforms.

**Comment by puffetto** [comment]
I confirm that there are only these two issues: isascii() and memmem().
Leaving the memmem() patch in place and adding a wild "int isascii(int);" implementation the code compiles and runs.

**Comment by puffetto** [comment]
Final note: after digging a bit it is not even tkrzw using isascii(), it is the STL library itself; there has been a similar "bug report" in the past on FreeBSD's, https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257827
The general consensus seem to be that _POSIX_C_SOURCE is only valid for 'C' code, not 'C++', as it requires a C99 compiler and as C++ bindings are not defined for POSIX.
Also on Solaris this is defined as undefined behaviour.

**Comment by estraier** [comment]
Now I understand the situation.
One bothering issue is that _POSIX_C_SOURCE is necessary on some platforms including MacOS to enable some POSIX API functions.
To me, saying "_POSIX_C_SOURCE is only valid for 'C' code, not 'C++'" sounds too much.
Calling POSIX "C" API from C++ code is a daily necessity for UNIX programmers.

Anyway, working code is much better than non-working code.  So, I'd like to take your suggestion.

**Comment by estraier** [comment]
Thanks for the suggestion.
I wish that the standard C++ library takes such a measure to encapsulate
messy things from application programmers...
Anyway, blacklisting some system names seems enough for the time being.
Let's see how it goes.

**Pull request merged**
